#!/usr/bin/env python3
"""generate_landing.py

Create a simple index.html inside data/reports that lists report files (sorted by mtime)
and highlights the latest report. This file will be published to GitHub Pages.
"""
from pathlib import Path
from datetime import datetime
import html

DATA_DIR = Path('data')
REPORT_DIR = DATA_DIR / 'reports'
REPORT_DIR.mkdir(parents=True, exist_ok=True)

def find_reports():
    files = [p for p in REPORT_DIR.iterdir() if p.is_file() and p.suffix in ('.html', '.htm')]
    files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return files

def render_index(reports):
    now = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')
    title = 'ePermits reports'
    items = []
    for p in reports:
        mtime = datetime.utcfromtimestamp(p.stat().st_mtime).strftime('%Y-%m-%d %H:%M')
        items.append({'name': p.name, 'mtime': mtime})

    latest = items[0]['name'] if items else None

    html_lines = [
        '<!doctype html>',
        '<html lang="en">',
        '<head>',
        '  <meta charset="utf-8">',
        f'  <title>{html.escape(title)}</title>',
        '  <meta name="viewport" content="width=device-width,initial-scale=1">',
        '  <style> body{font-family:Arial,Helvetica,sans-serif;padding:20px;max-width:900px;margin:auto} h1{margin-top:0} .list{margin-top:18px} .item{padding:8px;border-bottom:1px solid #eee} .latest{background:#f7f9ff;padding:8px;border-left:4px solid #3b82f6}</style>',
        '</head>',
        '<body>',
        f'  <h1>{html.escape(title)}</h1>',
        f'  <div>Generated: {now}</div>',
    ]

    if not items:
        html_lines += [
            '<p>No reports available yet.</p>',
            '</body>',
            '</html>',
        ]
        return '\n'.join(html_lines)

    if latest:
        html_lines += [f'  <h2>Latest: <a href="{html.escape(latest)}">{html.escape(latest)}</a></h2>']

    html_lines += ['  <div class="list">']
    for it in items:
        cls = 'item'
        if it['name'] == latest:
            cls = 'item latest'
        html_lines.append(f'    <div class="{cls}"><a href="{html.escape(it["name"])}">{html.escape(it["name"])}</a> <small>({it["mtime"]})</small></div>')

    html_lines += [
        '  </div>',
        '  <hr>',
        '  <footer><small>Reports generated by the ePermits pipeline.</small></footer>',
        '</body>',
        '</html>'
    ]
    return '\n'.join(html_lines)

def main():
    reports = find_reports()
    index_html = render_index(reports)
    out = REPORT_DIR / 'index.html'
    out.write_text(index_html, encoding='utf8')
    print('Wrote', out)

if __name__ == '__main__':
    main()
